language: node_js
node_js:
  - 13.14
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run test:coverage
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $travis_token
  local_dir: build
  on:
    branch: master